install-deps:
  stage: build
  image: gcc
  script:
    - pushd tests/gitlabCI
    - sh installDeps.sh
  artifacts:
    paths:
      - /opt/local/
      - installLog.log
    expire_in: 2 month

unit-test:
  stage: test
  image: gcc
  script:
    - export LD_LIBRARY_PATH=/opt/local/lib:$LD_LIBRARY_PATH
    - export LD_RUN_PATH=/opt/local/lib:$LD_RUN_PATH
    - make directories
    - make unit
    - make run
  dependencies:
    - install-deps

pages:
  stage: build
  image: alpine
  script:
    - apk update && apk add doxygen
    - apk add graphviz
    - doxygen doxy/dox_config
    - mv docs/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
  dependencies: []
