image: gcc

before_script:
  - pushd tests/gitlabCI
  - sh installDeps.sh

unit-tests:
  script:
    - export LD_LIBRARY_PATH=/opt/local/lib:$LD_LIBRARY_PATH
    - export LD_RUN_PATH=/opt/local/lib:$LD_RUN_PATH
    - make directories
    - make unit
    - make run
