image: gcc

cache:
  paths:
    - /opt/local

test:
  script:
    - pushd tests/gitlabCI
    - sh installDeps.sh
    - export LD_LIBRARY_PATH=/opt/local/lib:$LD_LIBRARY_PATH
    - export LD_RUN_PATH=/opt/local/lib:$LD_RUN_PATH
    - make directories
    - make unit
    - make run

pages:
  script:
    - apk update && apk add doxygen
    - doxygen doxy/dox_config
    - mv docs/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
