cache:
  paths:
    - /builds/adcox/Astrohelion/deps/
    - /builds/adcox/Astrohelion/data/

install-deps:
  stage: build
  image: gcc
  script:
    - pushd tests/gitlabCI
    - sh installDeps.sh
  only:
    - master
    - mainDev

unit-test:
  stage: test
  image: gcc
  script:
    - pushd tests/gitlabCI/
    - mkdir -p /root/.config/astrohelion
    - cp settings.xml /root/.config/astrohelion/user_settings.xml
    - cp body_data.xml /root/.config/astrohelion/body_data.xml
    - export LD_LIBRARY_PATH=/builds/adcox/Astrohelion/deps/installed/lib:$LD_LIBRARY_PATH
    - export LD_RUN_PATH=/builds/adcox/Astrohelion/deps/installed/lib:$LD_RUN_PATH
    - make directories
    - make unit
    - make run
  dependencies:
    - install-deps
  only:
    - master
    - mainDev

pages:
  stage: build
#   image: ubuntu:trusty
  image: aergus/latex
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -yq update
    - apt-get -yq install graphviz
    - apt-get -yq install doxygen
    # - apt-get -yq install latex dvips gs
    - doxygen doxy/dox_config
    - mv docs/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
