image: gcc

stages:
  - build
  - run

before_script:
  - pushd tests/gitlabCI
  - sh installDeps.sh

unit-tests:
  stage: build
  script:
    - make directories
    - make unit

unit-tests:
  stage: run
  script:
    - make run