cache:
  paths:
    - /builds/adcox/Astrohelion/deps/
    - /builds/adcox/Astrohelion/data/
    # - /root/.config/astrohelion/

install-deps:
  stage: build
  image: gcc
  script:
    - pushd tests/gitlabCI
    - sh installDeps.sh
  # artifacts:
  #   paths:
  #     - /builds/adcox/Astrohelion/deps/
  #     - /root/.config/astrohelion/
  #   expire_in: 2 month

unit-test:
  stage: test
  image: gcc
  script:
    - pushd tests/gitlabCI/
    - mkdir -p /root/.config/astrohelion
    - cp settings.xml /root/.config/astrohelion/user_settings.xml
    - cp body_data.xml /root/.config/astrohelion/body_data.xml
    - export LD_LIBRARY_PATH=/builds/adcox/Astrohelion/deps/installed/lib:$LD_LIBRARY_PATH
    - export LD_RUN_PATH=/builds/adcox/Astrohelion/deps/installed/lib:$LD_RUN_PATH
    - make directories
    - make unit
    - make run
  dependencies:
    - install-deps

pages:
  stage: build
  image: ubuntu:trusty
  script:
    - apt-get update && apt-get install graphviz && apt-get install doxygen
    - doxygen doxy/dox_config
    - mv docs/html/ public/
  artifacts:
    paths:
      - public
  # only:
  #   - master
