sudo: required

language: cpp

os:
  - linux

compiler:
  - g++-6

install:
  - pushd tests/travisCI
  - sudo ./installDependencies.sh

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
  - gcc --version
  - make all

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

notifications:
  email:
    on_success: never     #default is: change
    on_failure: always    #defaul is: always