sudo: required

language: cpp

os:
  - linux

compiler:
  - g++-5

install:
  - pushd tests/travisCI
  - sudo ./installDependencies.sh

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - make -C tests/travisCI

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5