/**
 *	@file AllIncludes.hpp
 *
 *	@brief Provides easy include for all headers in the Core library
 */

#include "AsciiOutput.hpp"
#include "Calculations.hpp"
#include "BodyData.hpp"
#include "Calculations.hpp"
#include "Constants.hpp"
#include "Constraint.hpp"
#include "CorrectionEngine.hpp"
#include "Event.hpp"
#include "Exceptions.hpp"
#include "Fam_cr3bp.hpp"
#include "FamMember_cr3bp.hpp"
#include "LinMotionEngine.hpp"
#include "MultShootData.hpp"
#include "Node.hpp"
#include "Nodeset.hpp"
#include "Nodeset_bc4bp.hpp"
#include "Nodeset_cr3bp.hpp"
#include "Segment.hpp"
#include "SimEngine.hpp"
#include "SysData.hpp"
#include "SysData_2bp.hpp"
#include "SysData_bc4bp.hpp"
#include "SysData_cr3bp.hpp"
#include "SysData_cr3bp_ltvp.hpp"
#include "Traj.hpp"
#include "Traj_2bp.hpp"
#include "Traj_bc4bp.hpp"
#include "Traj_cr3bp.hpp"
#include "Traj_cr3bp_ltvp.hpp"
#include "Utilities.hpp"