/**
 *	\file AllIncludes.hpp
 *
 *	\brief Provides easy include for all headers in the Core library
 */

#include "AsciiOutput.hpp"
#include "Arcset.hpp"
#include "Arcset_2bp.hpp"
#include "Arcset_bc4bp.hpp"
#include "Arcset_cr3bp.hpp"
#include "Arcset_cr3bp_lt.hpp"
#include "Arcset_periodic.hpp"
#include "BodyData.hpp"
#include "Calculations.hpp"
#include "Common.hpp"
#include "Constraint.hpp"
#include "ControlLaw_cr3bp_lt.hpp"
#include "ManifoldEngine.hpp"
#include "MultShootEngine.hpp"
#include "Event.hpp"
#include "Exceptions.hpp"
#include "Family_PO.hpp"
#include "Family_PO_cr3bp.hpp"
#include "LinMotionEngine_cr3bp.hpp"
#include "LinMotionEngine_cr3bp_lt.hpp"
#include "MultShootData.hpp"
#include "NatParamEngine.hpp"
#include "Node.hpp"
#include "PseudoArcEngine.hpp"
#include "Segment.hpp"
#include "SimEngine.hpp"
#include "SysData.hpp"
#include "SysData_2bp.hpp"
#include "SysData_bc4bp.hpp"
#include "SysData_cr3bp.hpp"
#include "SysData_cr3bp_lt.hpp"
#include "Utilities.hpp"